networks:
  dockernet:
    external:
     true
volumes:
  teleport_data:
    name: teleport_data
      

services:
  teleport.web:
    image: public.ecr.aws/gravitational/teleport-distroless:15.3.0
    container_name: teleport.web
    hostname: teleport.web
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./config:/etc/teleport
      - teleport_data:/var/lib/teleport
    labels:
      - traefik.enable=true
      - traefik.http.services.teleport.loadbalancer.server.port=3080
      # - traefik.http.services.teleport.loadbalancer.server.scheme=https
      - traefik.http.routers.teleport-rtr.entrypoints=http,https
      # - traefik.http.routers.teleport-http.rule=HostRegexp(`teleport.homestack.me`, `{subhost:[a-z]+}.teleport.homestack.me`)
      # - traefik.http.routers.teleport-http.rule=HostRegexp(`teleport.homestack.me`)
      # - traefik.http.routers.teleport-https.entrypoints=https
      # - traefik.http.routers.teleport-https.rule=HostRegexp(`teleport.homestack.me`, `{subhost:[a-z]+}.teleport.homestack.me`)
      - traefik.http.routers.teleport-rtr.rule=HostRegexp(`teleport.homestack.me`)
      - traefik.http.routers.teleport-rtr.tls=true
      - traefik.http.routers.teleport-rtr.tls.certresolver=development
      - traefik.http.routers.teleport-rtr.tls.domains[0].main=teleport.homestack.me
      - traefik.http.routers.teleport-rtr.tls.domains[0].sans=*.teleport.homestack.me