services:
  zabbix_postgres:
    image: postgres:16-alpine
    container_name: zabbix_postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=pasword
      - POSTGRES_USER=user
      - PGDATA=var/lib/postgres/data/pgdata
      
  zabbix_server:
    image: zabbix/zabbix-server-pgsql:alpine-trunk
    command: --init
    environment:
      - DB_SERVER_HOST=zabbix_postgres 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

      - ZBX_STARTREPORTWRITERS="2" 
      - ZBX_WEBSERVICEURL="http://zabbix-web-service:10053/report"


  zabbix-web-service:
    image: zabbix/zabbix-web-service
    environment:
      - ZBX_ALLOWEDIP="some-zabbix-server"
      - ZBX_LISTENPORT=10053
    #  = --cap-add=SYS_ADMIN

  some-zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql
    environment:
      - DB_SERVER_HOST=zabbix_postgres
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password 
      - ZBX_SERVER_HOST=zabbix_server 
      - PHP_TZ=UTC
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_PORT=5432