## traefik v3.yml

global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG
  format: common # | json

accessLog:
  filePath: /var/lib/traefik/traefik.log # Specify the path for the access log file
  format: json

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/config.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "kvruntime@proton.me"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: /var/lib/traefik/acme.json
      httpChallenge:
        entryPoint: http
  dev-letsencrypt:
    acme:
      email: kvruntime@proton.me
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: /var/lib/traefik/acme.json
      httpChallenge:
        entryPoint: http
