networks:
  dockernet:
    external:
      true

volumes:
  rocketchat.mongodb-data:
    name: rocketchat.mongodb-data

services:
  rocketchat.web:
    image: registry.rocket.chat/rocketchat/rocket.chat:develop
    restart: unless-stopped
    container_name: rocketchat.web
    networks:
      - dockernet
    environment:
      - MONGO_URL=mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@rocketchat.mongodb:27017/rocketchat?authSource=admin
      - MONGO_OPLOG_URL=mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@rocketchat.mongodb:27017/local?authSource=admin
      - DEPLOY_METHOD=docker
    #   - REG_TOKEN
    #   - ADMIN_USERNAME
    #   - ADMIN_PASS
    #   - ADMIN_EMAIL
    #   - INITIAL_USER
    #   - ADMIN_NAME
    depends_on:
      - rocketchat.mongodb
    ports:
      - 3000:3000
    env_file:
      - rocketchat.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.rocketchat.rule=Host(`${DOMAIN:-sub.domain.com}`)
      - traefik.http.routers.rocketchat.tls=true
      - traefik.http.routers.rocketchat.entrypoints=https
      - traefik.http.routers.rocketchat.tls.certresolver=develop
  rocketchat.mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: unless-stopped
    container_name: rocketchat.mongodb
    ports:
      - 27017:27017
    networks:
      - dockernet
    volumes:
      - rocketchat.mongodb-data:/bitnami/mongodb
    environment:
      - MONGODB_ENABLE_JOURNAL=false
      - ALLOW_EMPTY_PASSWORD=no
    env_file:
      - rocketchat.env
