networks:
  front_net:
    external: true
  dockernet:
    external: true

services:
  appsmith:
    env_file: appsmith.env
    image: index.docker.io/appsmith/appsmith-ce:v1.8.15 #release
    container_name: appsmith
    # networks:
    #   - front_net
    #   - dockernet
    # volumes:
    #     - /appdata/volumes/appsmith/_data:/appsmith-stacks
    restart: unless-stopped
    ports:
      - 9090:80
    environment:
      # - APPSMITH_MONGODB_URI=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}/appsmtih
      - APPSMITH_MONGODB_URI
    labels:
      - traefik.enable=true
      - traefik.http.routers.appsmith-rtr.entrypoints=http,https
      - traefik.http.routers.appsmith-rtr.rule=Host(`appsmith.homestack.me`)
      - traefik.http.routers.appsmith-rtr.tls=true
      - traefik.http.routers.appsmith-rtr.tls.certresolver=development
      - traefik.http.services.appsmith-svc.loadbalancer.server.port=80
