networks:
  dockernet:
    external:
      true

volumes:
  pgsql_data:
    name: pgsql_data

services:
  pgsql:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - dockernet
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demodb
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.pgsql-rtr.entrypoints=postgres
      - traefik.tcp.services.pgsql-svc.loadbalancer.server.port=5432
    
  pgadmin:
    image: dpage/pgadmin4:snapshot
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_ENABLE_TLS=false