networks:
  dockernet:
    external: true

volumes:
  portainer_data:
    name: portainer_data

services:
  portainer:
    image: portainer/portainer-ce:sts
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=http,https
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.local.kvruntime.com`)
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000
