networks:
  dockernet:
    external: true
volumes:
  grafana_data:
    name: grafana_data

services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    networks:
      - dockernet
    # ports:
    #   - 3000:3000
    environment:
      - GF_LOG_LEVEL=debug
      # - GF_INSTALL_PLUGINS=plug01,plug02,plug03,...
      # - GF_INSTALL_PLUGINS=https://github.com/VolkovLabs/custom-plugin.zip
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-rtr.entrypoints=http,https
      - traefik.http.routers.grafana-rtr.rule=Host(`grafana.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana-rtr.tls=true
      - traefik.http.routers.grafana-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.grafana-svc.loadbalancer.server.port=3000
# grafana-cli plugins install
